### ISSUE TITLE
If correlation is not enabled, the script will continue (create.ps1, line 96 had no else {throw }

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-V2-Template#9]

**Comment by JeroenBL** [comment]
Hi Rick,

After discussing within the team, we've decided not to use a throw within the template for now. Our considerations have been that we do not want to correlate, whether accidentally or due to missing correlation setup. Instead, we believe it makes more sense to attempt to create an account if that's the case.
